### ISSUE TITLE
Thank you and two possible bug fixes

### ISSUE THREAD

**Issue by naeloob** [jotego/jt8255#1]
Hola Jotego, en primer lugar muchas gracias por el modulo y todo tu trabajo.

Esta dos lineas : 
https://github.com/jotego/jt8255/blob/aadccef70b9ad66887ad916f3ebe2d90c815e5fe/hdl/jt8255.v#L176-L177
No deberían ser ? : 
```
            if( mode_a!=2'd00 )  if(!inte_a_ibf && !inte_a_obf) latch_c[INTRA] <= 0;
            if( mode_b ) if(!inte_b) latch_c[INTRB] <= 0;
```

De lo contrario en mode_a y mode_b = 0 se estan poniendo los bits 0 y 3 del puertoC/LatchC siempre a 0, y así no hay quien lea un teclado sin tener pulsaciones fantasma :)

Por otro lado : 
https://github.com/jotego/jt8255/blob/aadccef70b9ad66887ad916f3ebe2d90c815e5fe/hdl/jt8255.v#L99
Tal y como está solo guarda información en los registros en el flanco de subida del WRN, cuando , entiendo según la documentación que he visto, debería guardar cuando este en 0.
Es decir : 
`        if( write ) begin
`
Con estos cambios, lo tengo funcionando sin problemas.

Lo dicho muchas gracias por todo.

**Comment by jotego** [comment]
Muchas gracias por revisarlo.

He corregido el borrado de interrupciones, que efectivamente estaba mal:
https://github.com/jotego/jt8255/blob/4892f690d1e36f25df142ac1850687253bbc7226/hdl/jt8255.v#L176-L178

Sobre el flanco de subida, la documentación lo especifica así:

![imagen](https://user-images.githubusercontent.com/1863036/114503627-e8e95800-9c2d-11eb-9444-757f11c334ba.png)

El dato cambia mientras wrn está activo y es válido mientras wrn sube. O sea que los laches de entrada capturan en el flanco de subida de wrn. Eso puede causarte problemas si tu lógica cambia wrn y din en el mismo flanco de reloj. Si cambio a lachear cuando wrn está bajo, habría registros erróneos si din cambia durante ese tiempo.

He aplicado una solución intermedia que es lachear en el flanco de subida, pero con el último valor de din mientras wrn estaba bajo. Eso creo que funcionará con tu lógica también, sin romper los diagramas de tiempo del chip original.

Gracias de nuevo
